version: '3.8'

services:
  backend:
    build: ./src
    env_file:
      - ./.env
    ports:
      - '80:80'
    
  frontend:
    build: ./client
    ports:
      - '8501:8501'
    depends_on:
      - backend
